# Generated by Django 2.1.3 on 2018-11-19 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gasto_mensal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gastoprevisto',
            name='nome',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
