# Generated by Django 2.1.3 on 2018-11-21 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('previsao', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='previsto',
            old_name='pagamento',
            new_name='credito',
        ),
    ]
